// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKjk80fkvsHTd0nkxwj2mav7lxkrLaOSM',
    appId: '1:444691489092:web:e202ae3e634a6cac16b711',
    messagingSenderId: '444691489092',
    projectId: 'project1-20282',
    authDomain: 'project1-20282.firebaseapp.com',
    storageBucket: 'project1-20282.firebasestorage.app',
    measurementId: 'G-XS797NG1C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbVlFEGRt903XvBr38RfK8QLn5w1F-h14',
    appId: '1:444691489092:android:c2849fa8f1a2c9ce16b711',
    messagingSenderId: '444691489092',
    projectId: 'project1-20282',
    storageBucket: 'project1-20282.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ0wB71yWjwUsPYAVY5DaYXms0bhZbfQI',
    appId: '1:444691489092:ios:3f06c3a668954fc516b711',
    messagingSenderId: '444691489092',
    projectId: 'project1-20282',
    storageBucket: 'project1-20282.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ0wB71yWjwUsPYAVY5DaYXms0bhZbfQI',
    appId: '1:444691489092:ios:3f06c3a668954fc516b711',
    messagingSenderId: '444691489092',
    projectId: 'project1-20282',
    storageBucket: 'project1-20282.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKjk80fkvsHTd0nkxwj2mav7lxkrLaOSM',
    appId: '1:444691489092:web:83c76f8ccb53677216b711',
    messagingSenderId: '444691489092',
    projectId: 'project1-20282',
    authDomain: 'project1-20282.firebaseapp.com',
    storageBucket: 'project1-20282.firebasestorage.app',
    measurementId: 'G-JLB64ZPT30',
  );
}
